// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqkyazjhgfdtfatuuffd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxa3lhempoZ2ZkdGZhdHV1ZmZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NzM2MzcsImV4cCI6MjA2MjI0OTYzN30.PSWaZ6_kKQugV3GWzFnA5QdQzXehYK0M-NWapI9dY6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);